name: publish

on: [pull_request]

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}
      - name: Set up vars
        run: |
          REPO="$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')"
          echo "IMAGE=ghcr.io/${REPO}:${{ github.sha }}" >> $GITHUB_ENV     
      - name: Build the Docker image
        run: |
          docker build . --tag ${{ env.IMAGE }}
          docker run ${{ env.IMAGE }}
          docker push ${{ env.IMAGE }}